### ISSUE TITLE
Bug 无法为selectByExampleWithBLOBs 查询添加limit

### ISSUE THREAD

**Issue by zhuyeqing5828** [wucao/mybatis-generator-limit-plugin#5]

**Comment by tonyleecn** [comment]
是有这样的问题  
`<select` id="selectByExampleWithBLOBs" ......>
    select
    <if test="distinct">
      distinct
    </if>
    <include refid="Base_Column_List" />
    ,
    <include refid="Blob_Column_List" />
    from kuaixun
    <if test="_parameter != null">
      <include refid="Example_Where_Clause" />
    </if>
    <if test="orderByClause != null">
      order by ${orderByClause}
    </if>
  </select>`

**Comment by zhuyeqing5828** [comment]
该项目已经转移到新项目,最新项目已经解决这个问题.(相关消息参考主页)
[新项目地址]( https://github.com/wucao/mybatis-generator-mysql-plugin)
